#!/usr/bin/env bash
# Will Install and configure HAproxy on your (lb-01)load balancer server.
# -- will Configure HAproxy so that it send traffic to web-01 and web-02
# --to Distribute requests using a roundrobin algorithm
# -- to managed HAproxy via an init script
# --will configured servers with the right hostnames:
#   [STUDENT_ID]-web-01 and [STUDENT_ID]-web-02


sudo su
apt-get -y update
apt-get -y upgrade
apt-get -y install haproxy
sed -i 's/ENABLED=0/ENABLED=1/' /etc/default/haproxy
cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.original
sed -i "$ a\listen 540-lb-01\n\tbind *:80\n\tmode http\n\tbalance roundrobin\n\toption httpclose\n\toption forwardfor\n\tserver 112121-web-01 54.237.68.51:80 check\n\tserver 112121-web-02 54.174.135.52:80 check" /etc/haproxy/haproxy.cfg
service haproxy start
