#!/usr/bin/env bash
# shows contents of the file `/etc/passwd`.
# to dispaly username, user id, and user home directory path.

myfile="/etc/passwd"
while IFS= read -r line
do
    echo "$line" | cut -d":" -f1,3,6
done < "$myfile"
