#!/usr/bin/env bash
# a Bash script that displays:
# The content of the current directory
# In a list format
# Where only the part of the name after the first dash is displayed.

lis=$(ls)
for f in $lis
do
    find "$f" | cut -d- -f2
done
