#!/usr/bin/env bash
# a Bash script that displays all active IPv4 IPs
# on the machine it’s executed on.
# Will displays all acive IPv4 addresses on the machine.

ifconfig -a | grep inet | cut -d: -f2 | cut -d" "  -f1
